#!/bin/sh
#
# @name my_custom_quad
#
# @maintainer Robosix <contact@robotsix.net>
#

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:= my_custom_quad}

. ${R}etc/init.d/rc.mc_defaults

param set SIM_GZ_EN 1

param set SENS_EN_GPSSIM 1
param set SENS_EN_BAROSIM 1
param set SENS_EN_MAGSIM 1

param set CA_AIRFRAME 0
param set CA_ROTOR_COUNT 4

param set CA_ROTOR0_PX 0.3535533905932738
param set CA_ROTOR0_PY -0.35355339059327373
param set CA_ROTOR0_PZ 0
param set CA_ROTOR0_CT 30.0
param set CA_ROTOR0_KM -0.02

param set SIM_GZ_EC_FUNC1 101
param set SIM_GZ_EC_MIN1 0
param set SIM_GZ_EC_MAX1 1000

param set CA_ROTOR1_PX -0.35355339059327373
param set CA_ROTOR1_PY -0.3535533905932738
param set CA_ROTOR1_PZ 0
param set CA_ROTOR1_CT 30.0
param set CA_ROTOR1_KM 0.02

param set SIM_GZ_EC_FUNC2 102
param set SIM_GZ_EC_MIN2 0
param set SIM_GZ_EC_MAX2 1000

param set CA_ROTOR2_PX -0.35355339059327384
param set CA_ROTOR2_PY 0.35355339059327373
param set CA_ROTOR2_PZ 0
param set CA_ROTOR2_CT 30.0
param set CA_ROTOR2_KM -0.02

param set SIM_GZ_EC_FUNC3 103
param set SIM_GZ_EC_MIN3 0
param set SIM_GZ_EC_MAX3 1000

param set CA_ROTOR3_PX 0.3535533905932737
param set CA_ROTOR3_PY 0.35355339059327384
param set CA_ROTOR3_PZ 0
param set CA_ROTOR3_CT 30.0
param set CA_ROTOR3_KM 0.02

param set SIM_GZ_EC_FUNC4 104
param set SIM_GZ_EC_MIN4 0
param set SIM_GZ_EC_MAX4 1000


param set MPC_MANTHR_MIN 0.05
param set MPC_THR_MIN 0.05
param set MPC_THR_HOVER 0.28591956910991595

# In simulation, with no remote
param set COM_RC_IN_MODE 4
param set COM_OBL_RC_ACT 7
param set COM_OF_LOSS_T 1.0
param set COM_OBC_LOSS_T 1.0
param set NAV_RCL_ACT 0
param set NAV_DLL_ACT 0
param set COM_QC_ACT 0
param set GF_ACTION 0
param set COM_RC_OVERRIDE 0
param set COM_RCL_EXCEPT 7
param set COM_FAIL_ACT_T 0.0
param set FD_ACT_EN 0
param set FD_ESCS_EN 0
param set EKF2_REQ_VDRIFT 0.5