#!/bin/sh
#
# @name my_custom_quad
#
# @maintainer Robosix <contact@robotsix.net>
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:= my_custom_quad}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.3535533905932738
param set-default CA_ROTOR0_PY -0.35355339059327373
param set-default CA_ROTOR0_PZ 0
param set-default CA_ROTOR0_CT 30.0
param set-default CA_ROTOR0_KM -0.01

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MAX1 1000

param set-default CA_ROTOR1_PX -0.35355339059327373
param set-default CA_ROTOR1_PY -0.3535533905932738
param set-default CA_ROTOR1_PZ 0
param set-default CA_ROTOR1_CT 30.0
param set-default CA_ROTOR1_KM 0.01

param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MAX2 1000

param set-default CA_ROTOR2_PX -0.35355339059327384
param set-default CA_ROTOR2_PY 0.35355339059327373
param set-default CA_ROTOR2_PZ 0
param set-default CA_ROTOR2_CT 30.0
param set-default CA_ROTOR2_KM -0.01

param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MAX3 1000

param set-default CA_ROTOR3_PX 0.3535533905932737
param set-default CA_ROTOR3_PY 0.35355339059327384
param set-default CA_ROTOR3_PZ 0
param set-default CA_ROTOR3_CT 30.0
param set-default CA_ROTOR3_KM 0.01

param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 0
param set-default SIM_GZ_EC_MAX4 1000


param set-default MPC_MANTHR_MIN 0.01
param set-default MPC_THR_MIN 0.01
param set-default MPC_THR_HOVER 0.08175

# Use squared motor control signal
param set-default THR_MDL_FAC 1

# PID tuning
param set-default MC_ROLLRATE_K 0.5
param set-default MC_PITCHRATE_K 0.5
param set-default MC_YAW_P 1.0

# In simulation, with no remote
param set-default COM_RC_IN_MODE 4
param set-default COM_OBL_RC_ACT 7
param set-default COM_OF_LOSS_T 1.0
param set-default COM_OBC_LOSS_T 1.0
param set-default NAV_RCL_ACT 0
param set-default NAV_DLL_ACT 0
param set-default COM_QC_ACT 0
param set-default GF_ACTION 0
param set-default COM_RC_OVERRIDE 0
param set-default COM_RCL_EXCEPT 7
param set-default COM_FAIL_ACT_T 0.0
param set-default FD_ACT_EN 0
param set-default FD_ESCS_EN 0
param set-default EKF2_REQ_VDRIFT 0.5