site_name: PX4_ROS2_workspace Documentation
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - Simulation: simulation.md
  - Firmware: firmware.md
  - Holybro Pixhawk Jetson Baseboard Setup: holybro_pixhawk_jetson_baseboard_setup.md
  - Collecting offboard logs: collect_log.md
  - Repository Structure: structure.md
