FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git \
    cmake \
    g++ \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git
WORKDIR /Micro-XRCE-DDS-Agent
RUN git checkout 57d086216d01ec43121845d385894a25987f8a2c
WORKDIR /Micro-XRCE-DDS-Agent/build
RUN cmake ..
RUN make -s
RUN make install
RUN ldconfig /usr/local/lib

ENTRYPOINT [ "/usr/local/bin/MicroXRCEAgent","udp4","-p","8888" ]