#!/bin/sh
#
# @name {{ model_name }}
#
# @maintainer Robosix <contact@robotsix.net>
#

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:= {{ model_name }}}

. ${R}etc/init.d/rc.mc_defaults

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT {{ num_motors }}

{% for (px, py, pz) in motor_positions %}
param set-default CA_ROTOR{{ loop.index0 }}_PX {{ px }}
param set-default CA_ROTOR{{ loop.index0 }}_PY {{ -py }}
param set-default CA_ROTOR{{ loop.index0 }}_PZ {{ -pz }}
param set-default CA_ROTOR{{ loop.index0 }}_CT {{ max_motor_thrust }}
{% set km = -0.01 if (loop.index0 % 2 == 0 and first_motor_cw) or (loop.index0 % 2 != 0 and not first_motor_cw) else 0.01 %}
param set-default CA_ROTOR{{ loop.index0 }}_KM {{ km }}

param set-default SIM_GZ_EC_FUNC{{ loop.index0 + 1 }} {{ 101 + loop.index0 }}
param set-default SIM_GZ_EC_MIN{{ loop.index0 + 1 }} 0
param set-default SIM_GZ_EC_MAX{{ loop.index0 + 1 }} 1000

{% endfor %}

param set-default MPC_MANTHR_MIN 0.01
param set-default MPC_THR_MIN 0.01
param set-default MPC_THR_HOVER {{ weight * 9.81 / num_motors / max_motor_thrust }}

# Use squared motor control signal
param set-default THR_MDL_FAC 1

# PID tuning
param set-default MC_ROLLRATE_K 0.5
param set-default MC_PITCHRATE_K 0.5
param set-default MC_YAW_P 1.0

# In simulation, with no remote
param set-default COM_RC_IN_MODE 4
param set-default COM_OBL_RC_ACT 7
param set-default COM_OF_LOSS_T 1.0
param set-default COM_OBC_LOSS_T 1.0
param set-default NAV_RCL_ACT 0
param set-default NAV_DLL_ACT 0
param set-default COM_QC_ACT 0
param set-default GF_ACTION 0
param set-default COM_RC_OVERRIDE 0
param set-default COM_RCL_EXCEPT 7
param set-default COM_FAIL_ACT_T 0.0
param set-default FD_ACT_EN 0
param set-default FD_ESCS_EN 0
param set-default EKF2_REQ_VDRIFT 0.5
