name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: px4_fw_upload
            dockerfile: Dockerfile_fw_upload
            platforms: linux/amd64
          - image: px4_sitl_builder
            dockerfile: Dockerfile_sitl_builder
            platforms: linux/amd64
          - image: pymavlink
            dockerfile: Dockerfile_pymavlink
            platforms: linux/amd64
          - image: generate_airframe
            dockerfile: Dockerfile_generate_airframe
            platforms: linux/amd64
          - image: gz_sim
            dockerfile: Dockerfile_gz_sim
            platforms: linux/amd64
          - image: ros2_builder
            dockerfile: Dockerfile_ros2_builder
            platforms: linux/amd64
          - image: ros2_debug
            dockerfile: Dockerfile_ros2_debug
            platforms: linux/amd64
          - image: micro_dds_agent
            dockerfile: Dockerfile_micro_dds_agent
            platforms: linux/amd64, linux/arm64
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: robotsix/${{ matrix.image }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platforms }}
