name: Build and Push Docker Images

on:
  push:
    branches:
      - master
    paths:
      - "docker/**"

jobs:
  push_to_registry:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: px4_fw_upload
            dockerfile: Dockerfile_fw_upload
          - image: px4_sitl_builder
            dockerfile: Dockerfile_sitl_builder
          - image: pymavlink
            dockerfile: Dockerfile_pymavlink
          - image: generate_airframe
            dockerfile: Dockerfile_generate_airframe
          - image: gz_sim
            dockerfile: Dockerfile_gz_sim
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: robotsix/${{ matrix.image }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./docker
          file: ./docker/${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
