name: Test On Ubuntu Latest

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  test:
    name: Test On Ubuntu Latest
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Test generate_airframe.sh
        run: ${{ github.workspace }}/tests/test_generate_airframe.sh
